### ISSUE TITLE
Not displayed in Marketplace

### ISSUE THREAD

**Issue by payne911** [WhiteMemory99/Intellij-Python-Inlay-Params#28]
I can't find the plugin in Marketplace :(

![image](https://user-images.githubusercontent.com/38117856/202760809-51045f24-9237-4b0c-92f5-4ecf0353e2ad.png)

**Comment by payne911** [comment]
Ah, I'm using Android Studio.

**Comment by payne911** [comment]
![image](https://user-images.githubusercontent.com/38117856/213795161-c3ec133c-ede2-4b57-bc5f-4ae30ac318fb.png)

Wait, but if it works for "IntelliJ CE", shouldn't it work or Android Studio?

**Comment by WhiteMemory99** [comment]
JetBrains doesn't include Android Studio to the plugins targeting PyCharm compatible IDEs. That's just how it is, most likely because Android Studio is considered to be a completely separate product.

You could building the plugin yourself targeting Android Studio, I hope it works.

**Comment by payne911** [comment]
> You could try building the plugin yourself, targeting Android Studio. I hope it works.

I tried, but at my company we use build 212, whereas you built against 213. So manually installing the plugin gives me an error.

Are there non-compatible APIs that prevent you from building against 212?

**Comment by WhiteMemory99** [comment]
It was raised to 213 because there were compatibility issues with anything below at that time. You can try lowering it at your own risk.
