### ISSUE TITLE
__Init__(self, arg)

### ISSUE THREAD

**Issue by Karim-53** [WhiteMemory99/Intellij-Python-Inlay-Params#30]
Hi, thanks for this great plugin

Just a small bug: the plugin does not detect `self`.

![image](https://user-images.githubusercontent.com/33978275/213450396-4ce5b7d5-368e-4fc4-bfb3-cbfd0941fbac.png)

**Comment by WhiteMemory99** [comment]
Hello.
The thing is that you're not supposed to call your parent class constructor directly most of the time.
Use the [super()](https://docs.python.org/3/library/functions.html#super) built-in function to solve your problem in a nice and supported way.

`super().__init__(app, name_value_list, x_text, y_test, path=path)`

Still, I'm gonna look for a way to support direct calls like that in the future updates.
