### ISSUE TITLE
Support single argument hints

### ISSUE THREAD

**Issue by baterflyrity** [WhiteMemory99/Intellij-Python-Inlay-Params#36]
Hi!

Can please hint for single argument be added? 
As for now only 2+ arguments are hinted.

**Comment by WhiteMemory99** [comment]
Hi. Why would you need a hint for a single argument? As I see it, their primary purpose is to improve readability when you manage several arguments.

Still, I will probably add a settings option for that in the next update.

**Comment by baterflyrity** [comment]
Thanks a lot, it would be grateful.

> Why would you need a hint for a single argument?

Because sometimes single argument is not the only one.

```python
def decrease(step=1, start=2):
    return a - b

decrease(3) # -1
decrease(start=3) # 2
```

As you can see the function `decrease` call is non-obvious here. Ofcourse, this signature is pretty ugly but some signatures can not be changed from user code.

**Comment by Divaltor** [comment]
We would think about adding support for such rare cases without breaking the old behavior

**Comment by WhiteMemory99** [comment]
> Thanks a lot, it would be grateful.
> 
> > Why would you need a hint for a single argument?
> 
> Because sometimes single argument is not the only one.
> 
> ```python
> def decrease(step=1, start=2):
>     return start - step
> 
> decrease(3) # 3-- → -1 [wrong]
> decrease(start=3) # 3-- → 2 [ok]
> ```
> 
> As you can see the function `decrease` call is non-obvious here. Ofcourse, this signature is pretty ugly but some signatures can not be changed from user code.

The sample provided by you would actually show the parameter hint, since there are 2 parameters defined in the function. The hints only omitted if:

- There is only one parameter in the fuction.
- The only argument is unpacking (*/**)

Even so, I will add an option to the settings to show them even with a single parameter case, just to suit everyone's needs.
