### ISSUE TITLE
Missing support for PyCharm 2023.2.2

### ISSUE THREAD

**Issue by teodor-t-tenev** [WhiteMemory99/Intellij-Python-Inlay-Params#37]
No inlay hint params for 
<img width="327" alt="image" src="https://github.com/WhiteMemory99/Intellij-Python-Inlay-Params/assets/89847855/ec87fb93-4e17-4c11-b0f9-3f7fb91556ab">

**Comment by FieryDruid** [comment]
@teodor-t-tenev works correctly on 2023.2.3

![image](https://github.com/WhiteMemory99/Intellij-Python-Inlay-Params/assets/36041629/6527d671-3ef9-4a3f-a01c-bfd3a7b39467)

Try to check `Settings` -> `Editor` -> `Inlay Hints` -> `Types` -> `Python` -> `Type annotations` -> `General hints` option:

![image](https://github.com/WhiteMemory99/Intellij-Python-Inlay-Params/assets/36041629/f8e72a24-7428-4b44-9dbb-bc0098df052b)
