### ISSUE TITLE
version 0.3.3 is incompatible with IntelliJ version 2023.3

### ISSUE THREAD

**Issue by lavazais-sylvain** [WhiteMemory99/Intellij-Python-Inlay-Params#40]
since the last update of IntelliJ in 2023.3 (233.11799.241)

the plug-ins has stopped working.

![image](https://github.com/WhiteMemory99/Intellij-Python-Inlay-Params/assets/134276360/6988dc7d-7bfc-4896-8c4a-34d53969c11d)

```
IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 2, 2023
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Kotlin: 233.11799.241-IJ
```

**Comment by baterflyrity** [comment]
+1, Can you please update the plugin for the latest release?

**Comment by hwb96** [comment]
+1Error PluginPythonInlayParams'(versiono.3.3')isnot compatible withthe current version of the IDE,because itreguires build 232.*orolder but the currentbuildis PY-23 Can you fix this error?By losing this tool, I lost a good brother.
