### ISSUE TITLE
Add support to 2024.2

### ISSUE THREAD

**Issue by Ayfri** [WhiteMemory99/Intellij-Python-Inlay-Params#48]
Hey, this plugin is very cool !
Would it be possible to add support to 2024.2 ?
Thanks 👌

**Comment by WhiteMemory99** [comment]
The update with 2024.2 support will be available on the marketplace within a few business days. Otherwise, you can download and install it manually in the releases tab.

**Comment by Ayfri** [comment]
Thank you very much! 🙌
